name: Code Style

on:
  push:
    branches: [ master, mypy ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    name: ${{ matrix.PYVER }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - PYVER: current_arch
            SKIP_SHELLCHECK: 0
            SKIP_MYPY: 0
            SKIP_VULTURE: 0
            SKIP_RUFF: 0
            SKIP_PYPROJECT: 0

          - PYVER: python310_ubuntu_2204
            SKIP_SHELLCHECK: 1
            SKIP_MYPY: 1
            SKIP_VULTURE: 1
            SKIP_RUFF: 1
            SKIP_PYPROJECT: 1

    env:
      PYVER: ${{ matrix.PYVER }}
      SKIP_SHELLCHECK: ${{ matrix.SKIP_SHELLCHECK }}
      SKIP_MYPY: ${{ matrix.SKIP_MYPY }}
      SKIP_VULTURE: ${{ matrix.SKIP_VULTURE }}
      SKIP_RUFF: ${{ matrix.SKIP_RUFF }}

    steps:
    - uses: actions/checkout@v2

    - name: move dockerfiles into build context
      run: mv ./dockerfiles/* ./

    - name: switch base docker image
      run: sed -i -e 's|FROM archlinux:base-devel|FROM actionless/pikaur|' Dockerfile_${PYVER}

    - name: build docker image
      run: docker build . -f Dockerfile_${PYVER} -t oomox

    - name: run ci in docker
      run: docker run
        -e SKIP_SHELLCHECK=${SKIP_SHELLCHECK}
        -e SKIP_MYPY=${SKIP_MYPY}
        -e SKIP_VULTURE=${SKIP_VULTURE}
        -e SKIP_RUFF=${SKIP_RUFF}
        oomox:latest
        ./maintenance_scripts/lint.sh
